---
- name: Include bastion host tasks
  block:

    - name: Install geoipupdate
      ansible.builtin.apt:
        pkg: geoipupdate

    - name: /etc/GeoIP.conf
      ansible.builtin.copy:
        content: "{{ lookup('template', './geoip_conf.j2') }}"
        dest: /etc/GeoIP.conf
        owner: root
        group: root
        mode: '0600'
      when:
        - bastion.maxmind is defined
        - bastion.maxmind.id is defined
        - bastion.maxmind.key is defined

    - name: Crontab for geoipupdate
      ansible.builtin.cron:
        name: geoipupdate
        special_time: weekly
        user: root
        job: "/usr/bin/geoipupdate"
      when:
        - bastion.maxmind is defined
        - bastion.maxmind.id is defined
        - bastion.maxmind.key is defined

    - ansible.builtin.include_tasks: debian_terraform.yaml

  when: bastion is defined
