---
- name: Install geoipupdate
  ansible.builtin.apt:
    pkg: geoipupdate

- name: /etc/GeoIP.conf
  ansible.builtin.copy:
    content: "{{ lookup('template', './geoip_conf.j2') }}"
    dest: /etc/GeoIP.conf
    owner: root
    group: root
    mode: '0600'
  when:
    - maxmind is defined
    - maxmind.id is defined
    - maxmind.key is defined

- name: Update geoip mmdb crontab
  ansible.builtin.cron:
    name: geoipupdate
    special_time: weekly
    user: root
    job: "/usr/bin/geoipupdate"
  when:
    - maxmind is defined
    - maxmind.id is defined
    - maxmind.key is defined
