---
- name: Include Docker task lists
  block:

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} stable
        state: present

    - name: Install Docker packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      notify: restart docker
      with_items:
        - docker-ce
        - docker-ce-cli
        - docker-ce-rootless-extras
        - containerd.io

    - name: Ensure users are added to the docker group.
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: docker
        append: true
      loop: "{{ users }}"
