---
- name: Install HashiCorp keyring
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    keyring: /usr/share/keyrings/hashicorp-keyring.gpg
    state: present

- name: Install HashCorp amd64 repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64, signed-by=/usr/share/keyrings/hashicorp-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
  when: ansible_architecture == "x86_64"

- name: Install Terraform package
  ansible.builtin.apt:
    name: terraform
    state: latest
    update_cache: true
